openapi: 3.1.0
info:
  title: API Biblioteca
  version: 1.0.0
  description: Documentación de la API de Biblioteca

tags:
  - name: Authors
    description: Endpoints para gestionar autores

  - name: Categories
    description: Endpoints para gestionar categorías de libros

  - name: Users
    description: Endpoints para gestionar usuarios

  - name: Loans
    description: Endpoints para gestionar préstamos de libros

  - name: Histories
    description: Endpoints para gestionar historiales de feedback de préstamos


paths:

  ########################################
  #              AUTHORS
  ########################################

  /authors:
    get:
      tags: [Authors]
      summary: Obtener todos los autores
      responses:
        '200':
          description: Lista de autores
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/AuthorsDto'
                  timestamp:
                    type: string
                    example: "23/03/2026, 12:24:31"

    post:
      tags: [Authors]
      summary: Crear un nuevo autor
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AuthorsCreatedDh'
      responses:
        '201':
          description: Autor creado correctamente
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    $ref: '#/components/schemas/AuthorsDto'
                  timestamp:
                    type: string
                    example: "23/03/2026, 12:24:31"
              example:
                data:
                  authorId: 12
                  nameAuthor: "Gabriel García Márquez"
                timestamp: "23/03/2026, 12:24:31"

  /authors/id/{id}:
    get:
      tags: [Authors]
      summary: Buscar autor por ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            example: 3
      responses:
        '200':
          description: Autor encontrado
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    $ref: '#/components/schemas/AuthorsDto'
                  timestamp:
                    type: string
                    example: "23/03/2026, 12:24:31"

    delete:
      tags: [Authors]
      summary: Eliminar autor por ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            example: 3
      responses:
        '200':
          description: Resultado de la eliminación
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: boolean
                    example: true
                  timestamp:
                    type: string
                    example: "23/03/2026, 12:24:31"

    put:
      tags: [Authors]
      summary: Actualizar autor por ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            example: 3
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AuthorsUpdatedDh'
      responses:
        '200':
          description: Autor actualizado correctamente
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    $ref: '#/components/schemas/AuthorsDto'
                  timestamp:
                    type: string
                    example: "23/03/2026, 12:24:31"

  /authors/name/{name}:
    get:
      tags: [Authors]
      summary: Buscar autores por nombre
      parameters:
        - name: name
          in: path
          required: true
          schema:
            type: string
            example: "Gabriel"
      responses:
        '200':
          description: Lista de autores que coinciden con el nombre
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/AuthorsDto'
                  timestamp:
                    type: string
                    example: "23/03/2026, 12:24:31"


  ########################################
  #              PUBLISHERS
  ########################################

  /publishers:
    post:
      tags: [ Publishers ]
      summary: Crear un nuevo publisher
      description: Crea un nuevo registro de editorial en la base de datos.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PublishersCreatedRecordDh'
            example:
              publisherId: 6
              namePublisher: "HarperCollins"
              address: "Calle Nueva 10"
              city: "Madrid"
              province: "Madrid"
              postalCode: "28001"
              country: "España"
              phone: "+34-910000006"
              notes: "Editorial internacional"
      responses:
        '201':
          description: Publisher creado correctamente
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'
        '409':
          description: El publisherId ya existe
        '500':
          description: Error interno al guardar el publisher

    get:
      tags: [ Publishers ]
      summary: Obtener todos los publishers
      description: Devuelve la lista completa de editoriales.
      responses:
        '200':
          description: Lista de publishers
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PublishersDto'

  /publishers/id/{id}:
    get:
      tags: [ Publishers ]
      summary: Buscar publisher por ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            example: 1
      responses:
        '200':
          description: Publisher encontrado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'
        '404':
          description: No existe un publisher con ese ID

    put:
      tags: [ Publishers ]
      summary: Actualizar un publisher por ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            example: 1
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PublishersUpdatedRecordDh'
            example:
              publisherId: 1
              namePublisher: "Penguin Random House"
              address: "Calle Mayor 12"
              city: "Madrid"
              province: "Madrid"
              postalCode: "28013"
              country: "España"
              phone: "+34-910000001"
              notes: "Editorial internacional"
      responses:
        '200':
          description: Publisher actualizado correctamente
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'
        '404':
          description: No existe un publisher con ese ID
        '400':
          description: El publisherId del body no coincide con el ID del path
        '500':
          description: Error interno al actualizar el publisher

    delete:
      tags: [ Publishers ]
      summary: Eliminar un publisher por ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            example: 5
      responses:
        '200':
          description: Publisher eliminado correctamente
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: boolean
                    example: true
                  timestamp:
                    type: string
                    example: "23/03/2026, 12:24:31"
        '404':
          description: No existe un publisher con ese ID
        '409':
          description: No se puede eliminar porque tiene libros asociados
        '500':
          description: Error interno al eliminar el publisher

  /publishers/name/{name}:
    get:
      tags: [ Publishers ]
      summary: Buscar publishers por nombre
      parameters:
        - name: name
          in: path
          required: true
          schema:
            type: string
            example: "Planeta"
      responses:
        '200':
          description: Lista de publishers encontrados
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'
        '404':
          description: No existen publishers con ese nombre


  ########################################
  #              CATEGORIES
  ########################################

  /categories:
    get:
      tags: [ Categories ]
      summary: Obtener todas las categorías
      responses:
        '200':
          description: Lista de categorías
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/CategoriesDto'
                  timestamp:
                    type: string
                    example: "23/03/2026, 12:24:31"

    post:
      tags: [ Categories ]
      summary: Crear una nueva categoría
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CategoriesCreatedDh'
      responses:
        '201':
          description: Categoría creada correctamente
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    $ref: '#/components/schemas/CategoriesDto'
                  timestamp:
                    type: string
                    example: "23/03/2026, 12:24:31"
            example:
              data:
                categoryId: 10
                nameCategory: "Ficción"
              timestamp: "23/03/2026, 12:24:31"


  /categories/id/{id}:
    get:
      tags: [ Categories ]
      summary: Buscar categoría por ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            example: 3
      responses:
        '200':
          description: Categoría encontrada
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    $ref: '#/components/schemas/CategoriesDto'
                  timestamp:
                    type: string
                    example: "23/03/2026, 12:24:31"

    delete:
      tags: [ Categories ]
      summary: Eliminar categoría por ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            example: 3
      responses:
        '200':
          description: Resultado de la eliminación
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: boolean
                    example: true
                  timestamp:
                    type: string
                    example: "23/03/2026, 12:24:31"

    put:
      tags: [ Categories ]
      summary: Actualizar categoría por ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            example: 3
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CategoriesUpdatedDh'
      responses:
        '200':
          description: Categoría actualizada correctamente
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    $ref: '#/components/schemas/CategoriesDto'
                  timestamp:
                    type: string
                    example: "23/03/2026, 12:24:31"


  /categories/name/{name}:
    get:
      tags: [ Categories ]
      summary: Buscar categorías por nombre o subtema
      parameters:
        - name: name
          in: path
          required: true
          schema:
            type: string
            example: "Ficción"
      responses:
        '200':
          description: Lista de categorías encontradas
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/CategoriesDto'
                  timestamp:
                    type: string
                    example: "23/03/2026, 12:24:31"



  ########################################
  #                 USERS
  ########################################

  /users:
    get:
      tags: [ Users ]
      summary: Obtener todos los usuarios
      responses:
        '200':
          description: Lista de usuarios
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/UsersDto'
                  timestamp:
                    type: string
                    example: "23/03/2026, 12:24:31"

    post:
      tags: [ Users ]
      summary: Crear un nuevo usuario
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UsersCreatedDh'
      responses:
        '201':
          description: Usuario creado correctamente
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    $ref: '#/components/schemas/UsersDto'
                  timestamp:
                    type: string
                    example: "23/03/2026, 12:24:31"
            example:
              data:
                userId: 8
                nameUser: "Carlos Pérez"
                emailUser: "carlos@example.com"
              timestamp: "23/03/2026, 12:24:31"


  /users/id/{id}:
    get:
      tags: [ Users ]
      summary: Buscar usuario por ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            example: 8
      responses:
        '200':
          description: Usuario encontrado
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    $ref: '#/components/schemas/UsersDto'
                  timestamp:
                    type: string
                    example: "23/03/2026, 12:24:31"

    delete:
      tags: [ Users ]
      summary: Eliminar usuario por ID (borrado físico)
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            example: 8
      responses:
        '200':
          description: Resultado de la eliminación
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: boolean
                    example: true
                  timestamp:
                    type: string
                    example: "23/03/2026, 12:24:31"

    put:
      tags: [ Users ]
      summary: Actualizar usuario por ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            example: 8
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UsersUpdatedDh'
      responses:
        '200':
          description: Usuario actualizado correctamente
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    $ref: '#/components/schemas/UsersDto'
                  timestamp:
                    type: string
                    example: "23/03/2026, 12:24:31"


  /users/name/{name}:
    get:
      tags: [ Users ]
      summary: Buscar usuarios por nombre
      parameters:
        - name: name
          in: path
          required: true
          schema:
            type: string
            example: "Carlos"
      responses:
        '200':
          description: Lista de usuarios encontrados
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/UsersDto'
                  timestamp:
                    type: string
                    example: "23/03/2026, 12:24:31"


  /users/drop/id/{id}:
    delete:
      tags: [ Users ]
      summary: Borrado lógico de usuario por ID.
      description: >
        No se da de baja físicamente en la BD al usuario.
        Se pone a true el campo userDrop para indicar a la aplicación que es un usuario dado de baja.
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            example: 8
      responses:
        '200':
          description: Resultado del borrado lógico
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: boolean
                    example: true
                  timestamp:
                    type: string
                    example: "23/03/2026, 12:24:31"

  /users/password:
    put:
      tags: [ Users ]
      summary: Cambiar contraseña de un usuario
      description: >
        Cambia la contraseña de un usuario verificando DNI, email y teléfono.
        La nueva contraseña debe coincidir con `passwordRepeat` y cumple las reglas de seguridad.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UsersChangePassword'
            example:
              dni: "12345678A"
              email: "user@example.com"
              phone: "+34123456789"
              password: "NewPasswordAA1"
              passwordRepeat: "NewPasswordAA1"
      responses:
        '200':
          description: Contraseña cambiada correctamente
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: boolean
                    example: true
                  timestamp:
                    type: string
                    example: "23/03/2026, 12:24:31"
        '400':
          description: Error de validación o passwords no coinciden
        '404':
          description: No existe un usuario con los datos proporcionados
        '500':
          description: Error interno al guardar la nueva contraseña


  ########################################
  #                 BOOKS
  ########################################

  /books:
    get:
      tags: [ Books ]
      summary: Obtener todos los libros (versión completa)
      responses:
        '200':
          description: Lista completa de libros
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/BooksDto'
                  timestamp:
                    type: string
                    example: "23/03/2026, 12:24:31"

    post:
      tags: [ Books ]
      summary: Crear un nuevo libro
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BooksRecordDh'
      responses:
        '201':
          description: Libro creado correctamente
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    $ref: '#/components/schemas/BooksDto'
                  timestamp:
                    type: string
                    example: "23/03/2026, 12:24:31"
            example:
              data:
                isbn: "9781234567895"
                title: "Fundación"
                authorId: 1
              timestamp: "23/03/2026, 12:24:31"


  /books/public:
    get:
      tags: [ Books ]
      summary: Obtener todos los libros (vista pública)
      responses:
        '200':
          description: Lista pública de libros
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/BooksPublicDto'
                  timestamp:
                    type: string
                    example: "23/03/2026, 12:24:31"


  /books/private:
    get:
      tags: [ Books ]
      summary: Obtener todos los libros (vista privada)
      responses:
        '200':
          description: Lista privada de libros
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/BooksPublicDto'
                  timestamp:
                    type: string
                    example: "23/03/2026, 12:24:31"


  /books/isbn/{isbn}:
    get:
      tags: [ Books ]
      summary: Buscar libro por ISBN (versión completa)
      parameters:
        - name: isbn
          in: path
          required: true
          schema:
            type: string
            minLength: 10
            maxLength: 13
            example: "9781234567895"
      responses:
        '200':
          description: Libro encontrado
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    $ref: '#/components/schemas/BooksDto'
                  timestamp:
                    type: string
                    example: "23/03/2026, 12:24:31"

    delete:
      tags: [ Books ]
      summary: Eliminar libro por ISBN (incluye borrado físico de ficheros)
      parameters:
        - name: isbn
          in: path
          required: true
          schema:
            type: string
            minLength: 10
            maxLength: 13
            example: "9781234567895"
      responses:
        '200':
          description: Resultado de la eliminación
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: boolean
                    example: true
                  timestamp:
                    type: string
                    example: "23/03/2026, 12:24:31"

    put:
      tags: [ Books ]
      summary: Actualizar libro por ISBN (sin subir ficheros)
      parameters:
        - name: isbn
          in: path
          required: true
          schema:
            type: string
            minLength: 10
            maxLength: 13
            example: "9781234567895"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BooksRecordDh'
      responses:
        '200':
          description: Libro actualizado correctamente
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    $ref: '#/components/schemas/BooksDto'
                  timestamp:
                    type: string
                    example: "23/03/2026, 12:24:31"


  /books/public/isbn/{isbn}:
    get:
      tags: [ Books ]
      summary: Buscar libro por ISBN (vista pública)
      parameters:
        - name: isbn
          in: path
          required: true
          schema:
            type: string
            example: "9781234567895"
      responses:
        '200':
          description: Libro encontrado
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    $ref: '#/components/schemas/BooksPublicIsbnDto'
                  timestamp:
                    type: string
                    example: "23/03/2026, 12:24:31"


  /books/private/isbn/{isbn}:
    get:
      tags: [ Books ]
      summary: Buscar libro por ISBN (vista privada)
      parameters:
        - name: isbn
          in: path
          required: true
          schema:
            type: string
            example: "9781234567895"
      responses:
        '200':
          description: Libro encontrado
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    $ref: '#/components/schemas/BooksPublicIsbnDto'
                  timestamp:
                    type: string
                    example: "23/03/2026, 12:24:31"


  /books/title/{name}:
    get:
      tags: [ Books ]
      summary: Buscar libros por título (contiene)
      parameters:
        - name: name
          in: path
          required: true
          schema:
            type: string
            maxLength: 55
            example: "Fundación"
      responses:
        '200':
          description: Lista de libros encontrados
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/BooksPublicDto'
                  timestamp:
                    type: string
                    example: "23/03/2026, 12:24:31"


  /books/private/file/{isbn}:
    get:
      tags: [ Books ]
      summary: Obtener ruta del fichero PDF (privado)
      parameters:
        - name: isbn
          in: path
          required: true
          schema:
            type: string
            example: "9781234567895"
      responses:
        '200':
          description: Ruta del fichero PDF
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    $ref: '#/components/schemas/BooksFileDto'
                  timestamp:
                    type: string
                    example: "23/03/2026, 12:24:31"


  /books/public/file/{isbn}:
    get:
      tags: [ Books ]
      summary: Obtener ruta del fichero PDF (público)
      parameters:
        - name: isbn
          in: path
          required: true
          schema:
            type: string
            example: "9781234567895"
      responses:
        '200':
          description: Ruta del fichero PDF
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    $ref: '#/components/schemas/BooksFileDto'
                  timestamp:
                    type: string
                    example: "23/03/2026, 12:24:31"


  /books/{isbn}/files:
    put:
      tags: [ Books ]
      summary: Subir portada y fichero PDF de un libro
      parameters:
        - name: isbn
          in: path
          required: true
          schema:
            type: string
            example: "9781234567895"
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                bookCover:
                  type: string
                  format: binary
                bookFile:
                  type: string
                  format: binary
      responses:
        '200':
          description: Ficheros actualizados correctamente
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    $ref: '#/components/schemas/BooksDto'
                  timestamp:
                    type: string
                    example: "23/03/2026, 12:24:31"


  ########################################
  #                 LOANS
  ########################################

  /loans:
    get:
      tags: [ Loans ]
      summary: Obtener todos los préstamos
      responses:
        '200':
          description: Lista de préstamos
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/LoansDto'
                  timestamp:
                    type: string
                    example: "23/03/2026, 12:24:31"

    post:
      tags: [ Loans ]
      summary: Crear un nuevo préstamo
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoansRecordDh'
      responses:
        '201':
          description: Préstamo creado correctamente
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    $ref: '#/components/schemas/LoansDto'
                  timestamp:
                    type: string
                    example: "23/03/2026, 12:24:31"
            example:
              data:
                loanId: 5
                userId: 3
                isbn: "9781234567895"
                loanDate: "2026-03-23"
              timestamp: "23/03/2026, 12:24:31"


  /loans/id/{id}:
    get:
      tags: [ Loans ]
      summary: Buscar préstamo por ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            example: 5
      responses:
        '200':
          description: Préstamo encontrado
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    $ref: '#/components/schemas/LoansDto'
                  timestamp:
                    type: string
                    example: "23/03/2026, 12:24:31"

    delete:
      tags: [ Loans ]
      summary: Eliminar préstamo por ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            example: 5
      responses:
        '200':
          description: Resultado de la eliminación
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: boolean
                    example: true
                  timestamp:
                    type: string
                    example: "23/03/2026, 12:24:31"

    put:
      tags: [ Loans ]
      summary: Actualizar préstamo por ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            example: 5
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoansUpdateRecordDh'
      responses:
        '200':
          description: Préstamo actualizado correctamente
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    $ref: '#/components/schemas/LoansDto'
                  timestamp:
                    type: string
                    example: "23/03/2026, 12:24:31"


  /loans/userid/{id}:
    get:
      tags: [ Loans ]
      summary: Buscar préstamos por ID de usuario
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            example: 3
      responses:
        '200':
          description: Lista de préstamos del usuario
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/LoansDto'
                  timestamp:
                    type: string
                    example: "23/03/2026, 12:24:31"


  /loans/isbn/{isbn}:
    get:
      tags: [ Loans ]
      summary: Buscar préstamos por ISBN
      parameters:
        - name: isbn
          in: path
          required: true
          schema:
            type: string
            example: "9781234567895"
      responses:
        '200':
          description: Lista de préstamos del libro
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/LoansDto'
                  timestamp:
                    type: string
                    example: "23/03/2026, 12:24:31"


  ########################################
  #               HISTORIES
  ########################################

  /histories:
    get:
      tags: [ Histories ]
      summary: Obtener todos los historiales de feedback
      responses:
        '200':
          description: Lista de historiales
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/HistoriesDto'
                  timestamp:
                    type: string
                    example: "23/03/2026, 12:24:31"

    post:
      tags: [ Histories ]
      summary: Crear un nuevo historial de feedback
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/HistoriesRecordDh'
      responses:
        '201':
          description: Historial creado correctamente
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    $ref: '#/components/schemas/HistoriesDto'
                  timestamp:
                    type: string
                    example: "23/03/2026, 12:24:31"
            example:
              data:
                historyId: 3
                loanId: 5
                comment: "Todo correcto"
                createdAt: "2026-03-23"
              timestamp: "23/03/2026, 12:24:31"


  /histories/id/{id}:
    get:
      tags: [ Histories ]
      summary: Buscar historial por ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            example: 3
      responses:
        '200':
          description: Historial encontrado
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    $ref: '#/components/schemas/HistoriesDto'
                  timestamp:
                    type: string
                    example: "23/03/2026, 12:24:31"

    delete:
      tags: [ Histories ]
      summary: Eliminar historial por ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            example: 3
      responses:
        '200':
          description: Resultado de la eliminación
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: boolean
                    example: true
                  timestamp:
                    type: string
                    example: "23/03/2026, 12:24:31"

    put:
      tags: [ Histories ]
      summary: Actualizar historial por ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            example: 3
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/HistoriesUpdatedRecordDh'
      responses:
        '200':
          description: Historial actualizado correctamente
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    $ref: '#/components/schemas/HistoriesDto'
                  timestamp:
                    type: string
                    example: "23/03/2026, 12:24:31"


  /histories/loans/{id}:
    get:
      tags: [ Histories ]
      summary: Buscar historiales por ID de préstamo
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            example: 5
      responses:
        '200':
          description: Lista de historiales asociados al préstamo
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/HistoriesDto'
                  timestamp:
                    type: string
                    example: "23/03/2026, 12:24:31"


components:
  schemas:

    ########################################
    #              AUTHORS SCHEMAS
    ########################################

    AuthorsDto:
      type: object
      properties:
        authorId:
          type: integer
          example: 12
        nameAuthor:
          type: string
          example: "Gabriel García Márquez"

    AuthorsCreatedDh:
      type: object
      required:
        - nameAuthor
      properties:
        nameAuthor:
          type: string
          minLength: 4
          maxLength: 100
          pattern: "^[\\p{L} .'’\\-]+$"
          example: "Isabel Allende"

    AuthorsUpdatedDh:
      type: object
      required:
        - authorId
        - nameAuthor
      properties:
        authorId:
          type: integer
          minimum: 1
          example: 5
        nameAuthor:
          type: string
          minLength: 4
          maxLength: 100
          pattern: "^[\\p{L} .'’\\-]+$"
          example: "Mario Vargas Llosa"

    ########################################
    #              PUBLISHERS SCHEMAS
    ########################################

    PublishersCreatedRecordDh:
      type: object
      required:
        - publisherId
        - namePublisher
      properties:
        publisherId:
          type: integer
          example: 6
        namePublisher:
          type: string
          maxLength: 100
          example: "HarperCollins"
        address:
          type: string
          maxLength: 100
          example: "Calle Nueva 10"
        city:
          type: string
          maxLength: 40
          example: "Madrid"
        province:
          type: string
          maxLength: 30
          example: "Madrid"
        postalCode:
          type: string
          maxLength: 20
          example: "28001"
        country:
          type: string
          maxLength: 30
          example: "España"
        phone:
          type: string
          maxLength: 16
          example: "+34-910000006"
        notes:
          type: string
          maxLength: 255
          example: "Editorial internacional"

    PublishersUpdatedRecordDh:
      type: object
      required:
        - publisherId
        - namePublisher
      properties:
        publisherId:
          type: integer
          example: 1
        namePublisher:
          type: string
          maxLength: 100
          example: "Penguin Random House"
        address:
          type: string
          maxLength: 100
          example: "Calle Mayor 12"
        city:
          type: string
          maxLength: 40
          example: "Madrid"
        province:
          type: string
          maxLength: 30
          example: "Madrid"
        postalCode:
          type: string
          maxLength: 20
          example: "28013"
        country:
          type: string
          maxLength: 30
          example: "España"
        phone:
          type: string
          maxLength: 16
          example: "+34-910000001"
        notes:
          type: string
          maxLength: 255
          example: "Editorial internacional"

    PublishersDto:
      type: object
      properties:
        publisherId:
          type: integer
          example: 1
        namePublisher:
          type: string
          example: "Penguin Random House"
        address:
          type: string
          example: "Calle Mayor 12"
        city:
          type: string
          example: "Madrid"
        province:
          type: string
          example: "Madrid"
        postalCode:
          type: string
          example: "28013"
        country:
          type: string
          example: "España"
        phone:
          type: string
          example: "+34-910000001"
        notes:
          type: string
          example: "Editorial internacional"


    ########################################
    #              CATEGORIES SCHEMAS
    ########################################

    CategoriesDto:
      type: object
      properties:
        categoryId:
          type: integer
          example: 5
        nameCategory:
          type: string
          example: "Ciencia Ficción"
        subtopicCategory:
          type: string
          example: "Robots"

    CategoriesCreatedDh:
      type: object
      required:
        - nameCategory
      properties:
        nameCategory:
          type: string
          minLength: 3
          maxLength: 30
          pattern: "^[\\p{L} .'’\\-]+$"
          example: "Fantasía"
        subtopicCategory:
          type: string
          maxLength: 30
          example: "Épica"

    CategoriesUpdatedDh:
      type: object
      required:
        - categoryId
        - nameCategory
      properties:
        categoryId:
          type: integer
          minimum: 1
          example: 3
        nameCategory:
          type: string
          minLength: 3
          maxLength: 30
          pattern: "^[\\p{L} .'’\\-]+$"
          example: "Distopía"
        subtopicCategory:
          type: string
          maxLength: 30
          example: "Política"


    ########################################
    #              USERS SCHEMAS
    ########################################

    UsersDto:
      type: object
      properties:
        userId:
          type: integer
          example: 8
        fullname:
          type: string
          example: "Juan Carlos Díez"
        dni:
          type: string
          example: "44556677X"
        address:
          type: string
          example: "Calle Verde 15; 2 - E"
        city:
          type: string
          example: "Sevilla"
        province:
          type: string
          example: "Andalucía"
        postalCode:
          type: string
          example: "41001"
        country:
          type: string
          example: "España"
        phone:
          type: string
          example: "+34600000010"
        email:
          type: string
          example: "carlos@example.com"
        password:
          type: string
          example: "********"
        registrationDate:
          type: string
          example: "2026/01/25"
        userDrop:
          type: boolean
          example: false
        daysDisciplinary:
          type: integer
          example: 0
        role:
          $ref: '#/components/schemas/RoleEnum'



    UsersCreatedDh:
      type: object
      required:
        - fullname
        - dni
        - phone
        - email
        - password
      properties:
        fullname:
          type: string
          maxLength: 120
          pattern: "^[\\p{L}0-9\\s\\.,'’\\-\\u00B7]*$"
          example: "Carlos Díez"
        dni:
          type: string
          maxLength: 20
          example: "44556677X"
        address:
          type: string
          maxLength: 100
          example: "Calle Verde 13; 1 - D"
        city:
          type: string
          maxLength: 40
          example: "Sevilla"
        province:
          type: string
          maxLength: 30
          example: "Andalucía"
        postalCode:
          type: string
          maxLength: 20
          pattern: "^[A-Za-z0-9\\s\\-]{3,12}$"
          example: "41001"
        country:
          type: string
          maxLength: 30
          example: "España"
        phone:
          type: string
          maxLength: 16
          pattern: "^\\+?[0-9\\s\\-()]{6,20}$"
          example: "+34600000010"
        email:
          type: string
          maxLength: 120
          pattern: "^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,}$"
          example: "carlos@example.com"
        password:
          type: string
          minLength: 8
          maxLength: 25
          pattern: "^(?=(?:.*[A-Z]){2,})(?=(?:.*[a-z]){2,})(?=.*\\d).{8,25}$"
          example: "CARLOSdiez13"
        role:
          $ref: '#/components/schemas/RoleEnum'



    UsersUpdatedDh:
      type: object
      required:
        - userId
      properties:
        userId:
          type: integer
          minimum: 1
          example: 8
        fullname:
          type: string
          maxLength: 120
          pattern: "^[\\p{L}0-9\\s\\.,'’\\-\\u00B7]*$"
          example: "Juan Carlos Díez Cocoliso"
        address:
          type: string
          maxLength: 100
          example: "Calle Verde 15; 2 - E"
        city:
          type: string
          maxLength: 40
          example: "Sevilla"
        province:
          type: string
          maxLength: 30
          example: "Andalucía"
        postalCode:
          type: string
          maxLength: 20
          pattern: "^[A-Za-z0-9\\s\\-]{3,12}$"
          example: "41001"
        country:
          type: string
          maxLength: 30
          example: "España"
        phone:
          type: string
          maxLength: 16
          pattern: "^\\+?[0-9\\s\\-()]{6,20}$"
          example: "+34600000010"
        email:
          type: string
          maxLength: 120
          pattern: "^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,}$"
          example: "carlos@example.com"
        password:
          type: string
          minLength: 8
          maxLength: 25
          pattern: "^(?=(?:.*[A-Z]){2,})(?=(?:.*[a-z]){2,})(?=.*\\d).{8,25}$"
          example: "CARLOSdiez13"
        userDrop:
          type: boolean
          example: false
        daysDisciplinary:
          type: integer
          minimum: 0
          example: 0
        role:
          $ref: '#/components/schemas/RoleEnum'

    UsersChangePassword:
      type: object
      required:
        - dni
        - email
        - phone
        - password
        - passwordRepeat
      properties:
        dni:
          type: string
          maxLength: 20
          example: "12345678A"
        email:
          type: string
          maxLength: 120
          example: "user@example.com"
        phone:
          type: string
          maxLength: 16
          example: "+34123456789"
        password:
          type: string
          minLength: 8
          maxLength: 25
          example: "NewPasswordAA1"
        passwordRepeat:
          type: string
          minLength: 8
          maxLength: 25
          example: "NewPasswordAA1"


    ########################################
    #              BOOKS SCHEMAS
    ########################################

    BooksDto:
      type: object
      properties:
        isbn:
          type: string
          example: "9781234567895"
        title:
          type: string
          example: "Orgullo y Prejuicio"
        language:
          type: string
          example: "Español"
        pages:
          type: integer
          example: 279
        summary:
          type: string
          example: "Clásico romántico inglés."
        editionDate:
          type: string
          example: "1813-01-01"
        bookCover:
          type: string
          example: "uploads/cover/9781234567895_pride.jpg"
        bookFile:
          type: string
          example: "uploads/file/9781234567895_pride.pdf"
        authorId:
          type: integer
          example: 6
        authors:
          type: string
          example: "Jane Austen"
        publisherId:
          type: integer
          example: 1
        categoryId:
          type: integer
          example: 5

    BooksPublicDto:
      type: object
      properties:
        isbn:
          type: string
        title:
          type: string
        summary:
          type: string
        bookCover:
          type: string

    BooksPublicIsbnDto:
      type: object
      properties:
        isbn:
          type: string
        title:
          type: string
        summary:
          type: string
        bookCover:
          type: string
        pages:
          type: integer
        editionDate:
          type: string

    BooksFileDto:
      type: object
      properties:
        bookFile:
          type: string
          example: "uploads/file/9781234567895_pride.pdf"

    BooksRecordDh:
      type: object
      required:
        - isbn
        - authorId
        - publisherId
        - categoryId
      properties:
        isbn:
          type: string
          example: "9781234567895"
        title:
          type: string
          maxLength: 55
        pages:
          type: integer
        summary:
          type: string
          maxLength: 255
        editionDate:
          type: string
        language:
          type: string
        authors:
          type: string
        authorId:
          type: integer
        publisherId:
          type: integer
        categoryId:
          type: integer


    ########################################
    #              LOANS SCHEMAS
    ########################################

    LoansDto:
      type: object
      properties:
        loanId:
          type: integer
          example: 12
        loanDate:
          type: string
          format: date
          example: "2026-03-10"
        returnDate:
          type: string
          format: date
          example: "2026-03-17"
        userId:
          type: integer
          example: 9
        isbn:
          type: string
          example: "9781234567895"

    LoansRecordDh:
      type: object
      required:
        - userId
        - isbn
      properties:
        loanDate:
          type: string
          format: date
          description: Fecha del préstamo. Si no se envía, se asigna la fecha actual.
          example: "2026-03-10"
        returnDate:
          type: string
          format: date
          description: Fecha de devolución. Si no se envía, se asigna loanDate + 7 días.
          example: "2026-03-17"
        userId:
          type: integer
          minimum: 1
          example: 9
        isbn:
          type: string
          minLength: 10
          maxLength: 13
          example: "9781234567895"

    LoansUpdateRecordDh:
      type: object
      properties:
        loanDate:
          type: string
          format: date
          description: Nueva fecha del préstamo
          example: "2026-03-12"
        returnDate:
          type: string
          format: date
          description: Nueva fecha de devolución
          example: "2026-03-19"


    ########################################
    #             HISTORIES SCHEMAS
    ########################################

    HistoriesDto:
      type: object
      properties:
        historyId:
          type: integer
          example: 7
        dateFeedback:
          type: string
          format: date
          example: "2024-06-01"
        feedback:
          type: string
          example: "It es aterrador, me costó dormir después de leerlo."
        loanId:
          type: integer
          example: 7

    HistoriesRecordDh:
      type: object
      required:
        - loanId
      properties:
        dateFeedback:
          type: string
          format: date
          example: "2026-03-15"
        feedback:
          type: string
          maxLength: 255
          example: "Kafka en la orilla no me gustó."
        loanId:
          type: integer
          minimum: 1
          example: 14

    HistoriesUpdatedRecordDh:
      type: object
      required:
        - historyId
      properties:
        historyId:
          type: integer
          minimum: 1
          example: 9
        dateFeedback:
          type: string
          format: date
          example: "2026-03-16"
        feedback:
          type: string
          maxLength: 255
          example: "Actualizo mi opinión: ahora me gustó más."
        loanId:
          type: integer
          minimum: 1
          example: 14

    ########################################
    #           APIRESPONSE SCHEMAS
    ########################################

    ApiResponse:
      type: object
      properties:
        data:
          description: Contenido devuelto por el backend
        timestamp:
          type: string
          example: "23/03/2026, 12:24:31"


    RoleEnum:
      type: string
      description: Rol asignado al usuario dentro del sistema
      enum:
        - ADMIN
        - SUPPORT
        - USER
      example: USER
